version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "fmrsabino"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - "fmrsabino"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    reviewers:
      - "fmrsabino"
