repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.0
    hooks:
      - id: isort
        args: [ "--profile", "black", "--filter-files" ]
  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
        language_version: python3
