version: "3.9"

services:
  nginx:
    image: nginx:1.20-alpine
    links:
      - web:web
    env_file:
      - .env
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    depends_on:
      - web
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  web:
    build: .
    tty: true
    env_file:
      - .env
    command: gunicorn -c python:config.gunicorn config.wsgi -b 0.0.0.0:${GUNICORN_BIND_PORT}
    working_dir: /app/src
    depends_on:
      - db
