name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: "ubuntu-20.04"

    steps:
      - uses: "actions/checkout@v2"
      - name: "Test"
        run: |
          ./run ci:test
        env:
          DOCKER_BUILDKIT: "1"
